name: vmpbuild
on: [pull_request, push]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
 
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2
       
      - name: setup vsdevenv
        uses: seanmiddleditch/gha-setup-vsdevenv@master
 
      - name: Install Qt
        run: |
          pip install aqtinstall
          mkdir Qt
          cd Qt
          aqt install-qt windows desktop 5.12.12 win32_msvc2017
          aqt install-qt windows desktop 5.12.12 win64_msvc2017_64
         
      - name: build x64
        shell: cmd
        run: |
          set QTDIR=%GITHUB_WORKSPACE%\Qt\5.12.12\msvc2017_64
          set PATH=%PATH%;%QTDIR%\bin
          if exist build-libffi.bat (cmd.exe /c build-libffi.bat) else (echo build-libffi.bat not found & exit 1)
          if exist build-ultimate-x64.bat (cmd.exe /c build-ultimate-x64.bat) else (echo build-ultimate-x64.bat not found & exit 1)

      - name: Upload artifact (Windows)
        uses: actions/upload-artifact@v4
        with:
          name: vmp-windows
          path: bin

  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Qt and dependencies
        run: |
          brew update
          brew install python3
          python3 -m venv venv
          source venv/bin/activate
          python3 -m pip install aqtinstall
          mkdir Qt
          cd Qt
          python3 -m aqt install-qt mac desktop 5.12.12 clang_64

      - name: build macOS
        run: |
          source venv/bin/activate
          export QTDIR=$GITHUB_WORKSPACE/Qt/5.12.12/clang_64
          export PATH=$QTDIR/bin:$PATH
          chmod +x build-libffi.sh
          chmod +x build-ultimate-mac.sh
          if [ -f ./build-libffi.sh ]; then ./build-libffi.sh; else echo "build-libffi.sh not found"; exit 1; fi
          if [ -f ./build-ultimate-mac.sh ]; then ./build-ultimate-mac.sh; else echo "build-ultimate-mac.sh not found"; exit 1; fi

      - name: Upload artifact (macOS)
        uses: actions/upload-artifact@v4
        with:
          name: vmp-macos
          path: bin
